apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-cms
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Dzana-K/blog-cms.git
    targetRevision: main
    path: charts/blog-cms
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-cms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
